very minor typo in comments
ros2/ros1_bridge pull request #297
Opened 2020-11-23 15:39 UTC by Vicidel

as the documentation for parameter bridge is lacking, better to have comments without typo to avoid time waste on the user side

2020-11-23 23:14 UTC, fujitatomoya requested changes

2020-11-23 23:14 UTC, fujitatomoya commented on src/parameter_bridge.cpp
> +  // service: the name of the topic to bridge (e.g. '/service_name')
```suggestion
  // service: the name of the service to bridge (e.g. '/service_name')
```

2020-11-23 23:14 UTC, fujitatomoya commented on src/parameter_bridge.cpp
>    // type: the type of the topic to bridge (e.g. 'pkgname/srv/SrvName')
```suggestion
  // type: the type of the service to bridge (e.g. 'pkgname/srv/SrvName')
```

2020-11-24 05:25 UTC, nuclearsandwich approved these changes

2020-11-24 05:31 UTC, nuclearsandwich commented
@Vicidel these changes are probably small enough not to need a DCO but if you add one it will make the bot happy and we don't have to think about it.

2020-11-24 19:27 UTC, Vicidel commented
The DCO guide there doesn't work for me with error :
```
$ git push --force-with-lease origin patch-1
ERROR: Permission to ros2/ros1_bridge.git denied to Vicidel.
fatal: Could not read from remote repository.
```
I'll try to solve this for the future.

2020-11-25 18:53 UTC, nuclearsandwich commented
> The DCO guide there doesn't work for me with error :

I expect it is failing because I've applied the suggestions as a further commit on top of your changes. If you do a `git pull --rebase origin patch-1` before trying again I think that should do it.

2020-12-01 23:11 UTC, sloretz commented
@Vicidel friendly ping :) Thanks for the PR! Mind trying the fix @nuclearsandwich suggested?

2020-12-02 10:34 UTC, Vicidel commented
Sorry for the delay, I tested it but I still have errors:

`git pull --rebase origin patch-1
fatal: Couldn't find remote ref patch-1
`

`git push --force-with-lease origin patch-1
remote: Permission to ros2/ros1_bridge.git denied to Vicidel.
fatal: unable to access 'https://github.com/ros2/ros1_bridge.git/': The requested URL returned error: 403
`

2020-12-22 00:32 UTC, jacobperron approved these changes
Considering this is a small change to a comment, I'll just manually bypass the DCO bot in order to resolve this ticket.

2020-12-22 00:33 UTC, merged

2021-01-04 09:05 UTC, Vicidel commented
Sorry about this, I'm not used to open source and these kind of things. I will be careful in the future to comply to DCO.
Thank you for the merge