remove f-strings for dashing support
ros2/ros1_bridge pull request #306
Opened 2021-01-16 16:36 UTC by potentialdiffer

This fixes compilation issues on systems with Python versions older than 3.6 by removing f-Strings.  https://github.com/ros2/ros1_bridge/issues/305

2021-01-19 21:20 UTC, clalancette requested changes

2021-01-19 21:20 UTC, clalancette commented on ros1_bridge/__init__.py
> +            "file extension '.msg' or '.idl'")
```suggestion
            "message '%s/msg/%s' was not found in prefix '%s' with either"
            "file extension '.msg' or '.idl' %
            (ros2_msg.package_name, ros2_msg.message_name, ros2_msg.prefix_path))
```

(I think that is a lot easier to read)

2021-01-21 15:19 UTC, clalancette commented
CI:

- [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_packaging_linux&build=449)](https://ci.ros2.org/job/ci_packaging_linux/449/)

2021-01-21 16:30 UTC, clalancette commented
@potentialdiffer It looks like the build is not happy with the changes.  Can you take a look?

2021-01-22 06:04 UTC, fujitatomoya approved these changes
lgtm

2021-01-22 06:06 UTC, fujitatomoya commented
@clalancette 

> It looks like the build is not happy with the changes. Can you take a look?

isn't that because CI was kicked against focal:rolling? i think this one is supposed to be for bionic:dashing.

2021-01-22 08:28 UTC, potentialdiffer commented
It failed due to a missing symbol. I fixed it. Anyway @fujitatomoya has a point, it should be bionic:dashing.

2021-01-22 11:22 UTC, fujitatomoya commented
I started CI to rebuild https://ci.ros2.org/job/ci_packaging_linux/449/ with bionic:dashing. it tells me `Waiting for next available executor on` and pending. (build number is `450`)

2021-01-22 13:57 UTC, clalancette commented
> isn't that because CI was kicked against focal:rolling? i think this one is supposed to be for bionic:dashing.

You are right; I made that mistake, thanks for pointing it out.  However, the issues were in Python, so something else is going on.  @potentialdiffer you *may* need a `\` at the end of the string line continuations; I'm not sure.

2021-01-22 15:38 UTC, potentialdiffer commented
Can you have a look at the new error? I cannot see see how the new errors are related to the changes I did. https://ci.ros2.org/job/ci_packaging_linux/450/

2021-01-22 15:44 UTC, clalancette commented
> Can you have a look at the new error? I cannot see see how the new errors are related to the changes I did. https://ci.ros2.org/job/ci_packaging_linux/450/

No, it's my mistake again; that ros2.repos file is bogus for Dashing.  Sorry, I wasn't thinking straight when I ran this yesterday.  Here is another try:

- [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_packaging_linux&build=451)](https://ci.ros2.org/job/ci_packaging_linux/451/)

2021-01-22 17:33 UTC, clalancette commented
The flake8 errors are unrelated to this PR.  Going ahead and merging, thanks for fixing this.

2021-01-22 17:33 UTC, merged