The service name might provide more debug information than host:port details
ros2/ros1_bridge pull request #346
Opened 2022-03-07 12:18 UTC by Timple

2022-03-07 18:20 UTC, fujitatomoya requested changes
I think it is okay to print name.

2022-03-07 18:20 UTC, fujitatomoya commented on src/dynamic_bridge.cpp
> +    fprintf(stderr, "Failed to connect to %s (%s:%d)\n", name, host.data(), port);
```suggestion
    fprintf(stderr, "Failed to connect to %s (%s:%d)\n", name.data(), host.data(), port);
```

2022-03-07 18:53 UTC, fujitatomoya commented
@Timple could you address DCO failure https://github.com/ros2/ros1_bridge/pull/346/checks?check_run_id=5453577906?

2022-03-07 18:53 UTC, fujitatomoya approved these changes

2022-03-07 22:38 UTC, gbiggs approved these changes

2022-03-22 20:29 UTC, clalancette approved these changes

2022-03-22 20:30 UTC, merged